#!/usr/bin/env bash
# Embed an ONNX file as a C++ byte array into src/embedded/tiny_model_data.cpp.
#
# Usage:
#   ./scripts/embed_tiny_model.sh path/to/eupe_vit_t16_fp16.onnx
#
# Produces src/embedded/tiny_model_data.cpp which is compiled into the extension.

set -euo pipefail

if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <onnx-model-file>" >&2
    exit 1
fi

MODEL_FILE="$1"

if [ ! -f "$MODEL_FILE" ]; then
    echo "Error: model file not found: $MODEL_FILE" >&2
    exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJ_DIR="$(dirname "$SCRIPT_DIR")"
OUT="$PROJ_DIR/src/embedded/tiny_model_data.cpp"

SIZE=$(wc -c < "$MODEL_FILE" | tr -d ' ')
echo "Embedding $MODEL_FILE ($SIZE bytes) -> $OUT"

{
    echo "// Auto-generated by scripts/embed_tiny_model.sh. Do not edit."
    echo "// Source: $(basename "$MODEL_FILE")"
    echo "// Size:   $SIZE bytes"
    echo ""
    echo '#include "embedded_model.hpp"'
    echo ""
    echo "namespace duckdb {"
    echo ""
    echo "const uint8_t EUPE_TINY_MODEL_DATA[] = {"
    # xxd -i emits `unsigned char name[] = { ... };` - we slice out just the braces
    xxd -i < "$MODEL_FILE"
    echo "};"
    echo ""
    echo "const size_t EUPE_TINY_MODEL_SIZE = $SIZE;"
    echo ""
    echo "} // namespace duckdb"
} > "$OUT"

echo "Done. Now rebuild the extension: make release"
