#!/usr/bin/env bash
# Embed an ONNX file as a C++ byte array.
#
# Usage:
#   ./scripts/embed_tiny_model.sh <input.onnx> <output.cpp>
#
# Writes a self-contained .cpp defining EUPE_TINY_MODEL_DATA / EUPE_TINY_MODEL_SIZE
# to <output.cpp>. The output path may live outside the source tree (the build
# directory is the supported location); parent directories are created as needed.
#
# Exits non-zero on any failure (missing input, unwritable output, empty result).

set -euo pipefail

if [ "$#" -ne 2 ]; then
    echo "Usage: $0 <input.onnx> <output.cpp>" >&2
    exit 1
fi

MODEL_FILE="$1"
OUT="$2"

if [ ! -f "$MODEL_FILE" ]; then
    echo "Error: model file not found: $MODEL_FILE" >&2
    exit 1
fi

encode_bytes() {
    # Emit "0x.., 0x.., ..." lines, 12 bytes per line, comma-separated.
    # Compatible with xxd -i output style.
    if command -v xxd >/dev/null 2>&1; then
        xxd -i < "$1"
    elif command -v python3 >/dev/null 2>&1; then
        python3 - "$1" <<'PY'
import sys
with open(sys.argv[1], "rb") as f:
    buf = f.read()
for i in range(0, len(buf), 12):
    chunk = buf[i:i + 12]
    line = "  " + ", ".join(f"0x{b:02x}" for b in chunk)
    if i + 12 < len(buf):
        line += ","
    sys.stdout.write(line + "\n")
PY
    else
        echo "Error: neither xxd nor python3 found in PATH (one is required to embed bytes)" >&2
        return 1
    fi
}

OUT_DIR="$(dirname "$OUT")"
mkdir -p "$OUT_DIR"

if ! : > "$OUT.tmp"; then
    echo "Error: cannot write to $OUT.tmp (parent dir not writable?)" >&2
    exit 1
fi

SIZE=$(wc -c < "$MODEL_FILE" | tr -d ' ')
if [ "$SIZE" -le 0 ]; then
    echo "Error: model file is empty: $MODEL_FILE" >&2
    rm -f "$OUT.tmp"
    exit 1
fi

echo "Embedding $MODEL_FILE ($SIZE bytes) -> $OUT"

{
    echo "// Auto-generated by scripts/embed_tiny_model.sh. Do not edit."
    echo "// Source: $(basename "$MODEL_FILE")"
    echo "// Size:   $SIZE bytes"
    echo ""
    echo '#include "embedded_model.hpp"'
    echo ""
    echo "namespace duckdb {"
    echo ""
    echo "const uint8_t EUPE_TINY_MODEL_DATA[] = {"
    encode_bytes "$MODEL_FILE"
    echo "};"
    echo ""
    echo "const size_t EUPE_TINY_MODEL_SIZE = $SIZE;"
    echo ""
    echo "} // namespace duckdb"
} > "$OUT.tmp"

OUT_SIZE=$(wc -c < "$OUT.tmp" | tr -d ' ')
if [ "$OUT_SIZE" -lt "$SIZE" ]; then
    echo "Error: generated $OUT.tmp is smaller ($OUT_SIZE bytes) than input ($SIZE bytes); aborting" >&2
    rm -f "$OUT.tmp"
    exit 1
fi

mv "$OUT.tmp" "$OUT"
echo "Done: $OUT ($OUT_SIZE bytes)"
