# Embed a binary file as a C++ uint8_t array. Pure CMake — no bash, no python,
# no xxd. Run with `cmake -P cmake/embed_model.cmake -DIN=... -DOUT=...`.
#
# Why pure CMake: the duckdb community-extensions builders span Linux ARM64
# (no xxd in the image), Windows MinGW (a WSL bash.exe stub on PATH steals
# `bash` invocations), and macOS — so any external tool dependency creates a
# new portability hazard. CMake is required by every builder by definition.
#
# Output schema (matches src/include/embedded_model.hpp):
#     namespace duckdb {
#         const uint8_t  EUPE_TINY_MODEL_DATA[N];
#         const size_t   EUPE_TINY_MODEL_SIZE;
#     }

cmake_minimum_required(VERSION 3.10)

if(NOT DEFINED IN OR NOT DEFINED OUT)
    message(FATAL_ERROR "Usage: cmake -P embed_model.cmake -DIN=<input> -DOUT=<output.cpp>")
endif()

if(NOT EXISTS "${IN}")
    message(FATAL_ERROR "embed_model: input file not found: ${IN}")
endif()

file(SIZE "${IN}" _SIZE)
if(_SIZE EQUAL 0)
    message(FATAL_ERROR "embed_model: input file is empty: ${IN}")
endif()

get_filename_component(_OUT_DIR "${OUT}" DIRECTORY)
file(MAKE_DIRECTORY "${_OUT_DIR}")

get_filename_component(_IN_NAME "${IN}" NAME)
message(STATUS "embed_model: ${_IN_NAME} (${_SIZE} bytes) -> ${OUT}")

# Read as one long hex string and rewrite as "0x.., " comma-separated bytes.
# CMake regex on a 44M-char string takes ~30s for 22MB input on M1 — acceptable
# given this only runs at configure time (and at build time when the .onnx
# itself changes).
file(READ "${IN}" _HEX HEX)
string(REGEX REPLACE "(..)" "0x\\1, " _BYTES "${_HEX}")

# Write to a sibling .tmp first so an interrupted run never leaves a partial
# .cpp that downstream `if(EXISTS)` checks would mistake for valid output.
set(_TMP "${OUT}.tmp")
file(WRITE "${_TMP}"
"// Auto-generated by cmake/embed_model.cmake. Do not edit.
// Source: ${_IN_NAME}
// Size:   ${_SIZE} bytes

#include \"embedded_model.hpp\"

namespace duckdb {

const uint8_t EUPE_TINY_MODEL_DATA[] = { ${_BYTES} };

const size_t EUPE_TINY_MODEL_SIZE = ${_SIZE};

} // namespace duckdb
")

file(SIZE "${_TMP}" _TMP_SIZE)
if(_TMP_SIZE LESS _SIZE)
    file(REMOVE "${_TMP}")
    message(FATAL_ERROR
        "embed_model: generated ${_TMP} (${_TMP_SIZE} bytes) is smaller than input (${_SIZE} bytes); aborting")
endif()

file(RENAME "${_TMP}" "${OUT}")
message(STATUS "embed_model: wrote ${OUT} (${_TMP_SIZE} bytes)")
