#pragma once

#include <cstddef>
#include <cstdint>

namespace duckdb {

// Bundled EUPE ViT-T/16 ONNX model (FP16, ~12MB).
// The actual bytes live in src/embedded/tiny_model_data.cpp, generated by
// scripts/embed_tiny_model.sh from a real ONNX file.
//
// If the model has not been embedded (e.g. during development builds),
// EUPE_TINY_MODEL_SIZE is 0 and the bundled model is unavailable.
extern const uint8_t EUPE_TINY_MODEL_DATA[];
extern const size_t EUPE_TINY_MODEL_SIZE;

// Metadata about the embedded model
constexpr const char *EUPE_TINY_MODEL_NAME = "tiny";
constexpr const char *EUPE_TINY_MODEL_DESC = "EUPE ViT-T/16 (6M params, 192-d embeddings, FP16)";
constexpr int64_t EUPE_TINY_EMBED_DIM = 192;

} // namespace duckdb
